<form action="" class="generic-form" method="post">
    <fieldset>
        <legend>Formulaire d'inscription</legend>
        <ul>
            <li class="required">
                <label for="firstName">Prénom</label>
                <input id="firstName" type="text" name="firstName">
            </li>
            <li class="required">
                <label for="lastName">Nom</label>
                <input id="lastName" type="text" name="lastName">
            </li>
            <li class="required">
                <label for="email">Email</label>
                <input id="email" type="text" name="email">
            </li>
            <li class="required">
                <label for="password">Mot de passe</label>
                <input id="password" type="password" name="password">
            </li>
            <li>
                <label for="phone">Téléphone</label>
                <input id="phone" type="text" name="phone">
            </li>
            <li>
                <label for="address">Adresse</label>
                <input id="address" type="text" name="address">
            </li>
            <li>
                <label for="city">Ville</label>
                <input id="city" type="text" name="city">
            </li>
            <li>
                <label for="zipCode">codePostal</label>
                <input id="zipCode" type="text" name="zipCode">
            </li>
            <li>
                <button class="button button-primary">Envoyer</button>
            </li>
        </ul>
    </fieldset>
</form>