<form action="" class="generic-form" method="post">
    <fieldset>
        <legend>Formulaire d'inscription</legend>
        <ul>
            <li class="required">
                <label for="email">Email</label>
                <input id="email" type="text" name="email">
            </li>
            <li class="required">
                <label for="password">Mot de passe</label>
                <input id="password" type="password" name="password">
            </li>
            <li>
                <button class="button button-primary">Envoyer</button>
            </li>
        </ul>
    </fieldset>


</form>