<!-- Message de notification -->

<!-- Code HTML à écrire -->
<h2>Todo List</h2>
<ul class="done">
    <li>Customers - login</li>
    <li>Customers - register</li>
    <li>Traitement des erreurs</li>
    <li>Sessions</li>
    <li>Filtres d'interceptions</li>
    <li>Réaffichage des données du formulaire</li>
    <li>Flashbag</li>
    <li>Customers - sécurisation des mot de passes</li>
</ul>
<ul>
    <li>Gestion des Url Rewriting</li>
    <li>Reservations</li>
    <li>Validation des formulaire</li>
    <li>Panier</li>
    <li>Back Office - produits</li>
    <li>Back Office - commandes</li>
    <li>Back Office - customers</li>
    <li>Paiement</li>
</ul>

<!-- Liste des produits alimentaires -->
<table class="generic-table meal-list">
    <caption>Carte du restaurant</caption>
    <tbody>
    <?php foreach ($meals as $meal): ?>
        <tr>
            <td><img src="<?= $wwwUrl ?>/images/meals/<?= $meal['Photo']; ?>" alt="<?= $meal['Name']; ?>"></td>
            <td>
                <strong><?= $meal['Name']; ?></strong>
                <p><?= $meal['Description']; ?></p>
            </td>
            <td class="number"><strong><?= number_format($meal['SalePrice'], 2) ?></strong> €</td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>