<div id="admin">

    <h2>Panneau d'administration</h2>

    <table id="articles">
        <caption>Liste des articles</caption>
        <tr>
            <th>id</th>
            <th>titre</th>
            <th>auteur</th>
            <th>date</th>
            <th>actions</th>
        </tr>
        <?php foreach ($articles as $article): ?>
            <tr>
                <td><?= $article['id'] ?></td>
                <td><?= substr($article['title'], 0, 30) ?></td>
                <td><?= $article['author'] ?></td>
                <td><?= $article['creationDate'] ?></td>
                <td>
                    <a href="">edit</a>
                    <a href="">remove</a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>

    <table id="comments">
        <caption>Liste des Commentaires</caption>
        <tr>
            <th>id</th>
            <th>auteur</th>
            <th>contenu</th>
            <th>date</th>
            <th>article lié</th>
            <th>actions</th>
        </tr>
        <?php foreach ($comments as $comment): ?>
            <tr>
                <td><?= $comment['id'] ?></td>
                <td><?= htmlentities($comment['author']) ?></td>
                <td><?= htmlentities(substr($comment['content'], 0, 50)) ?></td>
                <td><?= $comment['creationDate'] ?></td>
                <td><?= $comment['articles_id'] ?></td>
                <td>
                    <a href="">remove</a>
                </td>
            </tr>
        <?php endforeach ?>
    </table>
</div>


<!--

<form class="container" method="post">
            <input type="hidden" name="article_id" value="<?= $article['id'] ?>">
            <fieldset>
                <legend>Ajouter un commentaire</legend>
                <ul>
                    <?php if (array_key_exists('error', $_GET)): ?>
                        <li class="error">
                            <p><?= $_GET['error'] ?></p>
                        </li>
                    <?php endif ?>
                    <?php if (array_key_exists('success', $_GET)): ?>
                        <li class="success">
                            <p><?= $_GET['success'] ?></p>
                        </li>
                    <?php endif ?>
                    <li>
                        <label for="author"  >Auteur</label>
                        <input id="author"  name="author">
                    </li>
                    <li>
                        <label for="email"  >Email</label>
                        <input id="email"  name="email">
                    </li>
                    <li>
                        <label for="content" >Commentaire</label>
                        <textarea id="content" name="content"></textarea>
                    </li>
                    <li>
                        <label></label>
                        <button name="add_comment">Envoyer</button>
                    </li>
                </ul>
            </fieldset>
        </form>
-->