<h2>Voici la page d'accueil</h2>
<p>Bienvenue sur mon blog</p>
<section>
    <h3>Liste des articles</h3>
    <article>
        Article 1
        <a href="index.php?page=article&id=1" title="lire l'article">Lire l'article 1</a>
    </article>

    <article>
        Article 2
        <a href="index.php?page=article&id=2" title="lire l'article">Lire l'article 2</a>
    </article>

    <article>
        Article 3
        <a href="index.php?page=article&id=3" title="lire l'article">Lire l'article 3</a>
    </article>
</section>
