<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>El Blogo</title>
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
</head>
<body>

<!-- en tête -->
<header class="container">
    <h1>El Blogo</h1>
</header>


<!-- contenu principal -->
<main>
    <?php include "pages/$template.phtml" ?>
</main>

<!-- pied de page -->
<footer class="container">
    <p>Je suis un pied de page</p>
</footer>
</body>
</html>