<form action="" class="generic-form" method="post">


    <fieldset>
        <legend>Connectez vous</legend>

        <?php if (!empty($errorMessage)): ?>
            <aside class="error-message">
                <h3>Il des erreurs dans votre formulaire</h3>
                <ul>
                    <li><?= $errorMessage ?></li>
                </ul>
            </aside>
        <?php endif ?>

        <ul>
            <li class="required">
                <label for="email">Email</label>
                <input id="email" type="text" name="email" value="<?= $email ?>">
            </li>
            <li class="required">
                <label for="password">Mot de passe</label>
                <input id="password" type="password" name="password" value="<?= $password ?>">
            </li>
            <li>
                <button class="button button-primary">Envoyer</button>
            </li>
        </ul>
    </fieldset>
</form>