<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Painter</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="style.css">
</head>
<body>
<header>
    <h1>Painter PHP</h1>
    <p>La POO en PHP c'est vraiment dla balle de cannard #selfpromo</p>
    <svg>
        <?= $html_shapes ?>
    </svg>
</header>

</body>
</html>